// src/app/components/game-canvas/game-canvas.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  NgZone,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild
} from '@angular/core';
import { CELL_SIZE, GRID_HEIGHT, GRID_WIDTH, LABEL_SIZE } from '../../../game/config';
import { DIRECTION_MAP, boardCenter, initialSnake } from '../../../game/movement';
import { renderGame } from '../../../game/rendering';
import { Label } from '../../../game/types';
import { randomBetween } from '../../../game/utils';
import type { Direction, GamePhase, Point, QuizQuestion } from '../../../types';

@Component({
  standalone: true,
  selector: 'app-game-canvas',
  template: `
    <div class="game-window" #wrapper>
      <canvas
        #canvas
        class="game-canvas"
        (pointerdown)="onPointerDown($event)"
        (pointermove)="onPointerMove($event)"
        (pointerup)="resetGesture()"
        (pointercancel)="resetGesture()"
        role="presentation"
      ></canvas>
    </div>
  `
})
export class GameCanvasComponent implements AfterViewInit, OnDestroy, OnChanges {
  @Input() phase: GamePhase = 'idle';
  @Input() stepMs = 250;
  @Input() question!: QuizQuestion;
  @Input() runId = 0;
  @Output() correct = new EventEmitter<void>();
  @Output() wrong = new EventEmitter<void>();
  @Output() gameOver = new EventEmitter<void>();

  @ViewChild('canvas') canvasRef?: ElementRef<HTMLCanvasElement>;
  @ViewChild('wrapper') wrapperRef?: ElementRef<HTMLDivElement>;

  snake: Point[] = [];
  labels: Label[] = [];
  head: Point = boardCenter();
  visibleArea = { width: GRID_WIDTH, height: GRID_HEIGHT };

  private lastTick = performance.now();
  private direction: Direction = 'right';
  private directionQueue: Direction[] = [];
  private animationId: number | null = null;
  private resizeObserver?: ResizeObserver;
  private touchStart: Point | null = null;
  private hasTurned = false;

  constructor(private zone: NgZone) {}

  ngOnChanges(changes: SimpleChanges) {
    if (changes['phase']) {
      const currentPhase = changes['phase'].currentValue as GamePhase;
      if (currentPhase === 'playing') {
        // Always start fresh when entering play (handles reset from game over).
        this.resetGameState();
        this.startGame();
      } else if (currentPhase === 'idle' || currentPhase === 'countdown') {
        this.resetGameState();
      }
    }

    if (changes['runId'] && !changes['phase'] && this.phase === 'playing') {
      // Force a fresh start when the run id changes without a phase change.
      this.resetGameState();
      this.startGame();
    }

    if (changes['question'] && this.phase === 'playing' && this.snake.length > 0) {
      this.labels = this.createLabels(this.snake);
      this.render();
    }
  }

  ngAfterViewInit() {
    this.updateViewport();
    this.observeResize();
    this.startLoop();
  }

  ngOnDestroy() {
    this.stopLoop();
    this.resizeObserver?.disconnect();
  }

  @HostListener('window:keydown', ['$event'])
  onKeyDown(event: KeyboardEvent) {
    if (event.key.startsWith('Arrow')) {
      event.preventDefault();
    }
  }

  @HostListener('window:keyup', ['$event'])
  onKeyUp(event: KeyboardEvent) {
    const directionMap: Record<string, Direction> = {
      ArrowUp: 'up',
      ArrowDown: 'down',
      ArrowLeft: 'left',
      ArrowRight: 'right'
    };
    const direction = directionMap[event.key];
    if (direction) {
      event.preventDefault();
      this.handleDirectionChange(direction);
    }
  }

  onPointerDown(event: PointerEvent) {
    this.touchStart = { x: event.clientX, y: event.clientY };
    this.hasTurned = false;
  }

  onPointerMove(event: PointerEvent) {
    if (!this.touchStart || this.hasTurned) return;
    const dx = event.clientX - this.touchStart.x;
    const dy = event.clientY - this.touchStart.y;
    if (Math.abs(dx) < 10 && Math.abs(dy) < 10) return;
    if (Math.abs(dx) > Math.abs(dy)) {
      this.handleImmediateDirectionChange(dx > 0 ? 'right' : 'left');
    } else {
      this.handleImmediateDirectionChange(dy > 0 ? 'down' : 'up');
    }
    this.hasTurned = true;
  }

  resetGesture() {
    this.touchStart = null;
    this.hasTurned = false;
  }

  private observeResize() {
    const wrapper = this.wrapperRef?.nativeElement;
    if (!wrapper) return;
    this.resizeObserver = new ResizeObserver(() => this.updateViewport());
    this.resizeObserver.observe(wrapper);
  }

  private updateViewport() {
    const canvas = this.canvasRef?.nativeElement;
    const wrapper = this.wrapperRef?.nativeElement;
    if (!canvas || !wrapper) return;
    const width = wrapper.clientWidth || GRID_WIDTH * CELL_SIZE;
    const height = wrapper.clientHeight || GRID_HEIGHT * CELL_SIZE;
    canvas.width = width;
    canvas.height = height;
    this.visibleArea = {
      width: Math.min(Math.floor(width / CELL_SIZE), GRID_WIDTH),
      height: Math.min(Math.floor(height / CELL_SIZE), GRID_HEIGHT)
    };
    this.render();
  }

  private startLoop() {
    this.zone.runOutsideAngular(() => {
      const loop = (timestamp: number) => {
        this.step(timestamp);
        this.animationId = requestAnimationFrame(loop);
      };
      this.animationId = requestAnimationFrame(loop);
    });
  }

  private stopLoop() {
    if (this.animationId !== null) {
      cancelAnimationFrame(this.animationId);
      this.animationId = null;
    }
  }

  private resetGameState() {
    this.snake = [];
    this.labels = [];
    this.head = boardCenter();
    this.direction = 'right';
    this.directionQueue = [];
    this.lastTick = performance.now();
    this.render();
  }

  private startGame() {
    this.direction = 'right';
    this.directionQueue = [];
    this.lastTick = performance.now();
    const newSnake = initialSnake();
    this.snake = newSnake;
    this.head = newSnake[0];
    this.labels = this.createLabels(newSnake);
    this.render();
  }

  private createLabels(currentSnake: Point[]): Label[] {
    const minX = 2;
    const maxX = GRID_WIDTH - 2 - LABEL_SIZE;
    const minY = 2;
    const maxY = GRID_HEIGHT - 2 - LABEL_SIZE;
    const taken = new Set(currentSnake.map((segment) => `${segment.x},${segment.y}`));

    const areaIsFree = (position: Point) => {
      for (let dx = 0; dx < LABEL_SIZE; dx += 1) {
        for (let dy = 0; dy < LABEL_SIZE; dy += 1) {
          if (taken.has(`${position.x + dx},${position.y + dy}`)) return false;
        }
      }
      return true;
    };

    const markArea = (position: Point) => {
      for (let dx = 0; dx < LABEL_SIZE; dx += 1) {
        for (let dy = 0; dy < LABEL_SIZE; dy += 1) {
          taken.add(`${position.x + dx},${position.y + dy}`);
        }
      }
    };

    const options: Label[] = [];
    this.question?.options.forEach((value) => {
      let position: Point;
      do {
        position = {
          x: randomBetween(minX, maxX),
          y: randomBetween(minY, maxY)
        };
      } while (!areaIsFree(position));
      markArea(position);
      options.push({ position, value });
    });
    return options;
  }

  private getPlannedDirection() {
    if (this.directionQueue.length) {
      return this.directionQueue[this.directionQueue.length - 1];
    }
    return this.direction;
  }

  private enqueueDirection(next: Direction) {
    const opposite: Record<Direction, Direction> = {
      up: 'down',
      down: 'up',
      left: 'right',
      right: 'left'
    };
    const plannedDirection = this.getPlannedDirection();
    if (opposite[next] === plannedDirection) return;
    if (this.directionQueue.length >= 2) {
      this.directionQueue.shift();
    }
    this.directionQueue.push(next);
  }

  private handleDirectionChange(next: Direction) {
    this.enqueueDirection(next);
  }

  private handleImmediateDirectionChange(next: Direction) {
    const opposite: Record<Direction, Direction> = {
      up: 'down',
      down: 'up',
      left: 'right',
      right: 'left'
    };
    if (opposite[next] === this.direction) return;
    this.directionQueue = [];
    this.direction = next;
  }

  private step(timestamp: number) {
    if (this.phase !== 'playing') return;
    if (timestamp - this.lastTick < this.stepMs) return;
    this.lastTick = timestamp;
    const queued = this.directionQueue.shift();
    const nextDirection = queued ?? this.direction;
    this.direction = nextDirection;

    const movement = DIRECTION_MAP[nextDirection];
    if (this.snake.length === 0) return;
    const newHead = { x: this.snake[0].x + movement.x, y: this.snake[0].y + movement.y };
    const hitsWall =
      newHead.x <= 0 || newHead.y <= 0 || newHead.x >= GRID_WIDTH - 1 || newHead.y >= GRID_HEIGHT - 1;
    const hitsBody = this.snake.some((segment) => segment.x === newHead.x && segment.y === newHead.y);
    if (hitsWall || hitsBody) {
      this.zone.run(() => this.gameOver.emit());
      return;
    }

    const labelIndex = this.labels.findIndex(
      (item) =>
        newHead.x >= item.position.x &&
        newHead.x < item.position.x + LABEL_SIZE &&
        newHead.y >= item.position.y &&
        newHead.y < item.position.y + LABEL_SIZE
    );
    const label = labelIndex >= 0 ? this.labels[labelIndex] : undefined;
    const grow = label?.value === this.question?.correct;
    const shrink = Boolean(label) && !grow;

    const nextLabels =
      labelIndex >= 0 ? this.labels.filter((_, index) => index !== labelIndex) : this.labels.slice();

    const updatedSnake = [newHead, ...this.snake];
    const targetLength = grow
      ? this.snake.length + 1
      : shrink
        ? Math.max(3, this.snake.length - 1)
        : this.snake.length;

    while (updatedSnake.length > targetLength) {
      updatedSnake.pop();
    }

    this.snake = updatedSnake;
    this.head = updatedSnake[0];
    this.labels = nextLabels;

    if (label) {
      if (grow) {
        this.zone.run(() => this.correct.emit());
      } else {
        this.zone.run(() => this.wrong.emit());
      }
    }

    this.render();
  }

  private render() {
    const canvas = this.canvasRef?.nativeElement;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    renderGame(ctx, {
      head: this.head,
      snake: this.snake,
      labels: this.labels,
      visibleArea: this.visibleArea
    });
  }
}

<div class="game-window" #wrapper>
  <canvas
    #canvas
    class="game-canvas"
    (pointerdown)="onPointerDown($event)"
    (pointermove)="onPointerMove($event)"
    (pointerup)="resetGesture()"
    (pointercancel)="resetGesture()"
    role="presentation"
  ></canvas>
</div>

// src/components/GameCanvas.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Direction, GamePhase, Point, QuizQuestion } from '../types';

interface GameCanvasProps {
  phase: GamePhase;
  question: QuizQuestion;
  onCorrect: () => void;
  onWrong: () => void;
  onGameOver: () => void;
}

const GRID_WIDTH = 30;
const GRID_HEIGHT = 30;
const CELL_SIZE = 26;
const LABEL_SIZE = 2;
const STEP_MS = 170;
const BOARD_BACKGROUND = '#0d1016';
const BOARD_DARK = '#11151b';
const BOARD_LIGHT = '#181d24';

const DIRECTION_MAP: Record<Direction, Point> = {
  up: { x: 0, y: -1 },
  down: { x: 0, y: 1 },
  left: { x: -1, y: 0 },
  right: { x: 1, y: 0 }
};

function rotateDirection(current: Direction, turn: 'left' | 'right'): Direction {
  const order: Direction[] = ['up', 'right', 'down', 'left'];
  const step = turn === 'right' ? 1 : -1;
  const index = order.indexOf(current);
  const nextIndex = (index + step + order.length) % order.length;
  return order[nextIndex];
}

interface Label {
  position: Point;
  value: number;
}

export default function GameCanvas({ phase, question, onCorrect, onWrong, onGameOver }: GameCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const [snake, setSnake] = useState<Point[]>([]);
  const [direction, setDirection] = useState<Direction>('right');
  const [queuedDirection, setQueuedDirection] = useState<Direction>('right');
  const [labels, setLabels] = useState<Label[]>([]);
  const [camera, setCamera] = useState({ width: GRID_WIDTH, height: GRID_HEIGHT });
  const touchStart = useRef<Point | null>(null);
  const lastTick = useRef(performance.now());
  const snakeRef = useRef<Point[]>([]);
  const labelsRef = useRef<Label[]>([]);

  const visibleArea = useMemo(() => ({
    width: Math.min(camera.width, GRID_WIDTH),
    height: Math.min(camera.height, GRID_HEIGHT)
  }), [camera.height, camera.width]);

  const head = snake[0] ?? { x: Math.floor(GRID_WIDTH / 2), y: Math.floor(GRID_HEIGHT / 2) };

  const createLabels = useCallback(
    (currentSnake: Point[]) => {
      const BORDER_BUFFER = 2;
      const minX = BORDER_BUFFER;
      const maxX = GRID_WIDTH - BORDER_BUFFER - LABEL_SIZE;
      const minY = BORDER_BUFFER;
      const maxY = GRID_HEIGHT - BORDER_BUFFER - LABEL_SIZE;
      const taken = new Set(currentSnake.map((segment) => `${segment.x},${segment.y}`));
      const areaIsFree = (position: Point) => {
        for (let dx = 0; dx < LABEL_SIZE; dx += 1) {
          for (let dy = 0; dy < LABEL_SIZE; dy += 1) {
            if (taken.has(`${position.x + dx},${position.y + dy}`)) return false;
          }
        }
        return true;
      };
      const markArea = (position: Point) => {
        for (let dx = 0; dx < LABEL_SIZE; dx += 1) {
          for (let dy = 0; dy < LABEL_SIZE; dy += 1) {
            taken.add(`${position.x + dx},${position.y + dy}`);
          }
        }
      };
      const options: Label[] = [];
      question.options.forEach((value) => {
        let position: Point;
        do {
          position = {
            x: randomBetween(minX, maxX),
            y: randomBetween(minY, maxY)
          };
        } while (!areaIsFree(position));
        markArea(position);
        options.push({ position, value });
      });
      return options;
    },
    [question.options]
  );

  useEffect(() => {
    snakeRef.current = snake;
  }, [snake]);

  useEffect(() => {
    labelsRef.current = labels;
  }, [labels]);

  useEffect(() => {
    if (phase === 'countdown' || phase === 'idle') {
      setSnake([]);
      setLabels([]);
      snakeRef.current = [];
      labelsRef.current = [];
      setDirection('right');
      setQueuedDirection('right');
      return;
    }
    if (phase === 'playing') {
      const startingDirection: Direction = 'right';
      setDirection(startingDirection);
      setQueuedDirection(startingDirection);
      lastTick.current = performance.now();
      const newSnake = initialSnake();
      setSnake(newSnake);
      snakeRef.current = newSnake;
      const newLabels = createLabels(newSnake);
      setLabels(newLabels);
      labelsRef.current = newLabels;
    }
  }, [phase]);

  useEffect(() => {
    if (phase !== 'playing') return;
    if (!snakeRef.current.length) return;
    const newLabels = createLabels(snakeRef.current);
    setLabels(newLabels);
    labelsRef.current = newLabels;
  }, [phase, createLabels, question]);

  useEffect(() => {
    const canvas = canvasRef.current;
    const wrapper = wrapperRef.current;
    if (!canvas || !wrapper) return;
    const resize = () => {
      const width = wrapper.clientWidth;
      const height = wrapper.clientHeight;
      canvas.width = width;
      canvas.height = height;
      setCamera({ width: Math.floor(width / CELL_SIZE), height: Math.floor(height / CELL_SIZE) });
    };
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(wrapper);
    return () => observer.disconnect();
  }, []);

  const handleDirectionChange = useCallback(
    (next: Direction) => {
      const opposite: Record<Direction, Direction> = {
        up: 'down',
        down: 'up',
        left: 'right',
        right: 'left'
      };
      if (opposite[next] === direction) return;
      setQueuedDirection(next);
    },
    [direction]
  );

  const queueTurn = useCallback((turn: 'left' | 'right') => {
    setQueuedDirection((current) => rotateDirection(current, turn));
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
        event.preventDefault();
      }
    };
    const onKeyUp = (event: KeyboardEvent) => {
      const turnMap: Record<string, 'left' | 'right'> = {
        ArrowLeft: 'left',
        ArrowRight: 'right'
      };
      const turn = turnMap[event.key];
      if (turn) {
        event.preventDefault();
        queueTurn(turn);
      }
    };
    window.addEventListener('keydown', onKeyDown);
    window.addEventListener('keyup', onKeyUp);
    return () => {
      window.removeEventListener('keydown', onKeyDown);
      window.removeEventListener('keyup', onKeyUp);
    };
  }, [queueTurn]);

  const handlePointerDown = (event: React.PointerEvent<HTMLCanvasElement>) => {
    touchStart.current = { x: event.clientX, y: event.clientY };
  };

  const handlePointerMove = (event: React.PointerEvent<HTMLCanvasElement>) => {
    if (!touchStart.current) return;
    const dx = event.clientX - touchStart.current.x;
    const dy = event.clientY - touchStart.current.y;
    if (Math.abs(dx) < 10 && Math.abs(dy) < 10) return;
    if (Math.abs(dx) > Math.abs(dy)) {
      handleDirectionChange(dx > 0 ? 'right' : 'left');
    } else {
      handleDirectionChange(dy > 0 ? 'down' : 'up');
    }
    touchStart.current = { x: event.clientX, y: event.clientY };
  };

  const step = useCallback(
    (timestamp: number) => {
      if (phase !== 'playing') return;
      if (timestamp - lastTick.current < STEP_MS) return;
      lastTick.current = timestamp;
      setDirection(queuedDirection);

      const movement = DIRECTION_MAP[queuedDirection];
      const currentSnake = snakeRef.current;
      if (currentSnake.length === 0) return;
      const newHead = { x: currentSnake[0].x + movement.x, y: currentSnake[0].y + movement.y };
      const hitsWall =
        newHead.x <= 0 || newHead.y <= 0 || newHead.x >= GRID_WIDTH - 1 || newHead.y >= GRID_HEIGHT - 1;
      const hitsBody = currentSnake.some((segment) => segment.x === newHead.x && segment.y === newHead.y);
      if (hitsWall || hitsBody) {
        onGameOver();
        return;
      }

      const labelIndex = labelsRef.current.findIndex(
        (item) =>
          newHead.x >= item.position.x &&
          newHead.x < item.position.x + LABEL_SIZE &&
          newHead.y >= item.position.y &&
          newHead.y < item.position.y + LABEL_SIZE
      );
      const label = labelIndex >= 0 ? labelsRef.current[labelIndex] : undefined;
      const grow = label?.value === question.correct;

      if (labelIndex >= 0) {
        setLabels((current) => current.filter((_, index) => index !== labelIndex));
      }

      const updatedSnake = [newHead, ...currentSnake];
      if (!grow) {
        updatedSnake.pop();
      }
      setSnake(updatedSnake);
      snakeRef.current = updatedSnake;

      if (label) {
        if (grow) {
          onCorrect();
        } else {
          onWrong();
        }
      }
    },
    [onCorrect, onGameOver, onWrong, queuedDirection, question.correct, phase]
  );

  const stepRef = useRef(step);
  useEffect(() => {
    stepRef.current = step;
  }, [step]);

  useEffect(() => {
    let animationId: number;
    const loop = (timestamp: number) => {
      stepRef.current(timestamp);
      animationId = requestAnimationFrame(loop);
    };
    animationId = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(animationId);
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const render = () => {
      const { width, height } = canvas;
      ctx.fillStyle = BOARD_BACKGROUND;
      ctx.fillRect(0, 0, width, height);

      const viewport = computeViewport(head, visibleArea.width, visibleArea.height);
      drawBackground(ctx, viewport);
      drawWalls(ctx, viewport);
      drawLabels(ctx, labels, viewport);
      drawSnake(ctx, snake, viewport);
    };
    render();
  }, [head, labels, snake, visibleArea.height, visibleArea.width]);

  return (
    <div className="game-window" ref={wrapperRef}>
      <canvas
        ref={canvasRef}
        className="game-canvas"
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        role="presentation"
      />
    </div>
  );
}

function drawBackground(ctx: CanvasRenderingContext2D, viewport: Viewport) {
  const { cellSize, width, height, x, y } = viewport;
  for (let cy = 0; cy < height; cy += 1) {
    for (let cx = 0; cx < width; cx += 1) {
      const worldX = x + cx;
      const worldY = y + cy;
      const useDark = (worldX + worldY) % 2 === 0;
      ctx.fillStyle = useDark ? BOARD_DARK : BOARD_LIGHT;
      ctx.fillRect(cx * cellSize, cy * cellSize, cellSize, cellSize);
    }
  }
}

function drawWalls(ctx: CanvasRenderingContext2D, viewport: Viewport) {
  const { cellSize, width, height } = viewport;
  const thickness = Math.min(cellSize, Math.floor(cellSize * 0.85));

  ctx.save();
  ctx.fillStyle = '#ffffff';
  ctx.shadowColor = 'rgba(255,255,255,0.35)';
  ctx.shadowBlur = Math.floor(thickness / 2);

  // Only draw the segments of the border that are currently in view.
  if (viewport.y === 0) {
    ctx.fillRect(0, 0, width * cellSize, thickness);
  }
  if (viewport.y + height === GRID_HEIGHT) {
    ctx.fillRect(0, height * cellSize - thickness, width * cellSize, thickness);
  }
  if (viewport.x === 0) {
    ctx.fillRect(0, 0, thickness, height * cellSize);
  }
  if (viewport.x + width === GRID_WIDTH) {
    ctx.fillRect(width * cellSize - thickness, 0, thickness, height * cellSize);
  }
  ctx.restore();
}

function drawSnake(ctx: CanvasRenderingContext2D, snake: Point[], viewport: Viewport) {
  const { cellSize, x, y } = viewport;
  const outline = Math.max(1, Math.floor(cellSize * 0.1));
  snake.forEach((segment, index) => {
    const sx = (segment.x - x) * cellSize;
    const sy = (segment.y - y) * cellSize;
    ctx.fillStyle = index === 0 ? '#0ecb81' : '#1f9b76';
    ctx.fillRect(sx, sy, cellSize, cellSize);
    ctx.lineWidth = outline;
    ctx.strokeStyle = '#ffffff';
    ctx.strokeRect(sx + outline / 2, sy + outline / 2, cellSize - outline, cellSize - outline);
    if (index === 0) {
      ctx.fillStyle = '#0b1726';
      ctx.fillRect(sx + cellSize * 0.6, sy + cellSize * 0.3, cellSize * 0.12, cellSize * 0.12);
      ctx.fillRect(sx + cellSize * 0.6, sy + cellSize * 0.6, cellSize * 0.12, cellSize * 0.12);
    }
  });
}

function drawLabels(ctx: CanvasRenderingContext2D, labels: Label[], viewport: Viewport) {
  const { cellSize, x, y, width, height } = viewport;
  const labelPixelSize = cellSize * LABEL_SIZE;
  labels.forEach((label) => {
    const inView =
      label.position.x < x + width &&
      label.position.x + LABEL_SIZE > x &&
      label.position.y < y + height &&
      label.position.y + LABEL_SIZE > y;

    if (!inView) return;

    const lx = (label.position.x - x) * cellSize;
    const ly = (label.position.y - y) * cellSize;
    ctx.fillStyle = '#ffd166';
    ctx.beginPath();
    ctx.roundRect(lx + 4, ly + 4, labelPixelSize - 8, labelPixelSize - 8, Math.floor(labelPixelSize / 6));
    ctx.fill();
    ctx.fillStyle = '#16314f';
    ctx.font = `${Math.floor(cellSize * 0.8)}px sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(String(label.value), lx + labelPixelSize / 2, ly + labelPixelSize / 2);
  });
}

function randomBetween(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function initialSnake(): Point[] {
  const center = { x: Math.floor(GRID_WIDTH / 2), y: Math.floor(GRID_HEIGHT / 2) };
  return [center, { x: center.x - 1, y: center.y }, { x: center.x - 2, y: center.y }];
}

interface Viewport {
  x: number;
  y: number;
  width: number;
  height: number;
  cellSize: number;
}

function computeViewport(head: Point, width: number, height: number): Viewport {
  const cellSize = CELL_SIZE;
  const x = clamp(head.x - Math.floor(width / 2), 0, GRID_WIDTH - width);
  const y = clamp(head.y - Math.floor(height / 2), 0, GRID_HEIGHT - height);
  return { x, y, width, height, cellSize };
}

function clamp(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, value));
}
